first_snowflake/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views
from reservations.views import EquipmentViewSet, CategoryViewSet, ReservationViewSet

from rest_framework import routers


router = routers.DefaultRouter()
router.register('equipment', EquipmentViewSet, 'eqquipment')
router.register('category', CategoryViewSet, 'category')
router.register('reservation', ReservationViewSet, 'reservation')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.mainpage),
    path('about/', views.aboutpage),
    path('equipment/', include('reservations.urls')),
    path('users/', include('users.urls')),

    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservations/urls.py
from django.urls import path

from . import views


app_name = 'reservations'

urlpatterns = [
    path('', views.EquipmentListView.as_view(), name='equipment_list'),
    path('<int:pk>', views.EquipmentDetailView.as_view(), name='equipment_detail'),
    path('<int:equipment_id>/reserve', views.DetailView.as_view(), name='reserve'),
    path('delete/<int:pk>', views.ReservationDeleteView.as_view(), name='reservation_delete'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register"),
    path('login/', views.CustomLoginView.as_view(), name="login"),
    path('logout/', views.CustomLogoutView.as_view(), name="logout"),
    path('account/', views.Account.as_view(), name="account"),
    path('ajax/check_email/', views.EmailValidationView.as_view(), name='check_email'),
    path('ajax/check_password/', views.PasswordValidationView.as_view(), name='check_password'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# from phonenumber_field.modelfields import PhoneNumberField

class CustomUser(AbstractUser):
    username = models.CharField(max_length=20, unique=False)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=9)

    USERNAME_FIELD = 'email'  # Login via email (don't need backeds.py)
    REQUIRED_FIELDS = ['username', 'phone_number'] 

    def __str__(self):
        return self.email
    

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email

    class Meta:
        verbose_name = "User Profile"
        verbose_name_plural = "Users Profiles"

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django import forms
import re

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ("username", "email", "phone_number", "password1", "password2",)
        
    # Validate email is unique
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError("This email address is already in use.")
        return email

    # Validate phone number only digits (and 9 digits long)
    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        digits = re.sub(r'\D', '', str(phone_number))  # remove any non-digit chars
        if len(digits) != 9:
            raise forms.ValidationError("Enter a valid 9-digit phone number.")
        return phone_number

    # (Optional) Username validations
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if len(username) < 3:
            raise forms.ValidationError("Username must be at least 3 characters long.")
        return username


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ("username", "email", "phone_number",)


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(label="Email",)

    class Meta:
        model = CustomUser
        fields = ("username", "password")

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.urls import reverse_lazy, reverse

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.edit import CreateView
from django.views import View

from .models import CustomUser

from .forms import CustomUserCreationForm, CustomAuthenticationForm

from reservations.models import Reservation

from django.http import JsonResponse
from django.core.validators import validate_email
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError


class RegisterView(CreateView):
    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("reservations:equipment_list")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.success_url)
    

class EmailValidationView(View):
    def get(self, request, *args, **kwargs):
        email = request.GET.get('email', '').strip()
        if not email:
            return JsonResponse({'error': 'Email is required.'}, status=400)
        try:
            validate_email(email)
        except ValidationError:
            return JsonResponse({'error': 'Invalid email format.'}, status=400)
        if CustomUser.objects.filter(email=email).exists():
            return JsonResponse({'exists': True})
        return JsonResponse({'exists': False})
    

class PasswordValidationView(View):
    def get(self, request, *args, **kwargs):
        password = request.GET.get('password', '')
        try:
            validate_password(password)
            return JsonResponse({"valid": True})
        except ValidationError as e:
            return JsonResponse({"valid": False, "errors": e.messages})

# def register_view(request):
#     if request.method == "POST":
#         form = CustomUserCreationForm(request.POST)          
#         if form.is_valid():
#             login(request, form.save())
#             return redirect("reservations:equipment_list")
#     else:
#         form = CustomUserCreationForm()
#     return render(request, 'users/register.html', { 'form': form })


class CustomLoginView(LoginView):
    template_name = "users/login.html"
    authentication_form = CustomAuthenticationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy("reservations:equipment_list")

# def login_view(request):
#     if request.method == "POST":
#         form = CustomAuthenticationForm(data=request.POST)
#         if form.is_valid():
#             login(request, form.get_user())
#             if 'next' in request.POST:
#                 return redirect(request.POST.get('next'))
#             else:
#                 return redirect("reservations:equipment_list")
#     else:
#         form = CustomAuthenticationForm(request.POST)
#     return render(request, 'users/login.html', { 'form': form })


class CustomLogoutView(LogoutView):
    pass

# def logout_view(request):
#     if request.method == "POST":
#         logout(request)
#         return redirect("/")
    

class Account(LoginRequiredMixin, ListView):
    model = Reservation
    template_name = "users/account.html"
    context_object_name = 'user_reservations'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user)
        return qs
    
# def account_view(request):
#     user_reservations = Reservation.objects.filter(user=request.user)
#     return render(request, 'users/account.html', { 'user_reservations': user_reservations})

users/templates/users/account.html
{% extends "layout.html" %}

{% block title %}
    User Account
{% endblock title %}

{% block content %}
<div class="container account-container">
    <p class="header">Reservation List</p>
    
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-primary" role="alert">
            {{ message }}
          </div>
        {% endfor %}
    {% endif %}

    <ul class="list-group list-group-flush">
        {% for reservation in user_reservations %}
            <li class="list-group-item d-flex justify-content-between align-items-start con_user_reservation">
                <div class="ms-2 me-auto">
                    <a class="nav-link user_reservation">
                        {{ reservation.equipment }}: {{ reservation.start_date|date:"D d.m.Y" }} - {{ reservation.end_date|date:"D d.m.Y" }}
                    </a> 
                </div>               

                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal{{ reservation.id }}">
                    Cancel reservation
                </button>
                
                <!-- Modal -->
                <div class="modal fade" id="modal{{ reservation.id }}" tabindex="-1" aria-labelledby="modalLabel{{ reservation.id }}" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h1 class="modal-title fs-5" id="modal{{ reservation.id }}">Cancel reservation</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <div>{{ reservation.equipment}}</div>
                                <div>{{ reservation.start_date }} - {{ reservation.end_date }}</div>
                                <div>Are you sure you want to cancel your reservation?</div>                        
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Back</button>
                                <form class="form-with-validation" action="{% url 'reservations:reservation_delete' reservation.id %}" method="POST">
                                    {% csrf_token %}
                                    {{ form }}
                                    <button type="submit" class="btn btn-primary" id="liveAlertBtn">Confirm</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>                   
            </li>
        {% endfor %}
    </ul>                 
</div>
{% endblock content %}

users/templates/users/login.html
<!DOCTYPE html>
{% load static %}
{% load form_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Login
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="d-flex align-items-center py-4 bg-body-tertiary login-body">
    <main class="form-signin w-100 m-auto login-view">
        <div class="container login-container">
            <form class="rounded-3 login-form-container" id="loginForm" method="POST">
                {% csrf_token %}
                <p class="login-title">Login</p>
                {% if form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ form.non_field_errors.0 }}
                    </div>
                {% endif %}

                <!-- Username (Email) Field -->
                <div class="form-floating mb-3">
                    {{ form.username|add_class:"form-control" }}
                    <label for="{{ form.username.id_for_label }}">Email address</label>
                  </div>

                <!-- Password input -->
                <div class="form-floating mb-3">
                    {{ form.password|add_class:"form-control" }}
                    <label for="{{ form.password.id_for_label }}">Password</label>
                </div>
                <button class="btn btn-primary w-100 py-2" type="submit">Continue</button>
                <p class="mt-5 mb-3 text-body-secondary">Don't have a Snowflake account? 
                    <a href="{% url 'users:register' %}">Register now!</a>
                </p>
            </form>
        </div>
        
    </main>

    <script src="{% static 'js/main.js' %}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

users/templates/users/register.html
<!DOCTYPE html>
{% load static %}
{% load form_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Sign Up
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="d-flex align-items-center py-4 bg-body-tertiary registration-body">
    
<div class="container-fluid">
    <div class="row g-0">      
      <!-- Left side: Banner Image -->
      <div class="col-md-5 col-lg-5 p-0 banner">
        <img class="banner-img" src="{{ REGISTER_REGISTRATION_BANNER }}" alt="Registration banner">
      </div>

      <!-- Right side: Registration Form -->
      <div class="col-md-7 col-lg-7 d-flex justify-content-center align-items-center form-section">
        <div class="register-form-container">
          <form method="POST">
            {% csrf_token %}       
            <p class="login-title">Sign up</p>

            <!-- Email -->
            <div class="form-floating login-form-input mb-3">
                {{ form.email|add_class:"form-control" }}
                <label for="{{ form.email.id_for_label }}">Email address</label>
                {% if form.email.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.email.errors.0 }}
                    </div>
                {% endif %}
                <div id="email-error-message" class="invalid-feedback d-none"></div> 
            </div>

            <!-- Name -->
            <div class="form-floating login-form-input mb-3">
                {{ form.username|add_class:"form-control" }}
                <label for="{{ form.username.id_for_label }}">First name</label>
                {% if form.username.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.username.errors.0 }}
                    </div>
                {% endif %}
                <div id="name-error-message" class="invalid-feedback d-none"></div> 
            </div>

            <!-- Phone number -->
            <div class="form-floating login-form-input mb-3">
                {{ form.phone_number|add_class:"form-control" }}
                <label for="{{ form.phone_number.id_for_label }}">Phone number</label>
                {% if form.phone_number.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.phone_number.errors.0 }}
                    </div>
                {% endif %}
                <div id="phone-error-message" class="invalid-feedback d-none"></div> 
            </div>

            <!-- Password1 -->
            <div class="form-floating login-form-input mb-3">
                {{ form.password1|add_class:"form-control" }}
                <label for="{{ form.password1.id_for_label }}">Password</label>
                {% if form.password1.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.password1.errors.0 }}
                    </div>
                {% endif %}
                <div id="password1-error-message" class="invalid-feedback d-none"></div> 
            </div>

            <!-- Password2 -->
            <div class="form-floating login-form-input mb-3">
                {{ form.password2|add_class:"form-control" }}
                <label for="{{ form.password2.id_for_label }}">Confirm password</label>
                {% if form.password2.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.password2.errors.0 }}
                    </div>
                {% endif %}
                <div id="password2-error-message" class="invalid-feedback d-none"></div> 
            </div>

            <button class="btn btn-primary w-100 py-2" type="submit">Register</button>            
            <p class="mt-3 mb-3 text-small">By creating an account, you agree to the Terms of Service. For more information about Snowflake's privacy practices, see the Snowflake Privacy Statement. We'll occasionally send you account-related emails.
            </p>
            <p class="mt-5 mb-3 text-body-secondary">Do you already have a Snowflake account? 
                <a href="{% url 'users:login' %}">&#160; Log in &rarr;</a>
            </p>             
        </form>
        </div>
      </div>
    </div>
  </div>   

    <script src="{% static 'js/register_validation.js' %}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>