first_snowflake/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views
from reservations.views import EquipmentViewSet, CategoryViewSet, ReservationViewSet

from rest_framework import routers


router = routers.DefaultRouter()
router.register('equipment', EquipmentViewSet, 'eqquipment')
router.register('category', CategoryViewSet, 'category')
router.register('reservation', ReservationViewSet, 'reservation')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.mainpage),
    path('about/', views.aboutpage),
    path('equipment/', include('reservations.urls')),
    path('users/', include('users.urls')),

    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservations/urls.py
from django.urls import path

from . import views


app_name = 'reservations'

urlpatterns = [
    path('', views.EquipmentListView.as_view(), name='equipment_list'),
    path('<int:pk>', views.EquipmentDetailView.as_view(), name='equipment_detail'),
    path('<int:equipment_id>/reserve', views.DetailView.as_view(), name='reserve'),
    path('delete/<int:pk>', views.ReservationDeleteView.as_view(), name='reservation_delete'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register"),
    path('login/', views.CustomLoginView.as_view(), name="login"),
    path('logout/', views.CustomLogoutView.as_view(), name="logout"),
    path('account/', views.Account.as_view(), name="account"),
    path('ajax/check_email/', views.EmailValidationView.as_view(), name='check_email'),
    path('ajax/check_password/', views.PasswordValidationView.as_view(), name='check_password'),
]

templates/about.html
{% extends "layout.html" %}

{% block title %}
    About
{% endblock title %}

{% block content %}
    <div class="container">
        <p class="header">About Us</p>
        <p>Oops! This site is under construction. We're working on something great. Stay tuned!</p>
        <p>Check out <a href="/">Home</a> page.</p>
    </div>
{% endblock content %}

templates/home.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
    <div id="carouselExampleAutoplaying"  class="carousel slide carousel-container" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="d-flex justify-content-center align-items-center carousel-img">
                    <img src="{{ HOME_TEST1 }}" class="d-block w-100 img-fluid" alt="...">
                    <div class="carousel-cover">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>If you can't control the weather, at least control your setup.</h5>
                            <p>If you can't control the weather, at least control your setup.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="d-flex justify-content-center align-items-center carousel-img">
                    <img src="{{ HOME_TEST2 }}" class="d-block w-100 img-fluid" alt="...">
                    <div class="carousel-cover">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>If your skis look retro but weren't meant to… it's time.</h5>
                            <p>If your skis look retro but weren't meant to… it's time.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="d-flex justify-content-center align-items-center carousel-img">
                    <img src="{{ HOME_TEST3 }}" class="d-block w-100 img-fluid" alt="...">
                    <div class="carousel-cover">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Snow falls. Riders rise. Good gear makes legends.</h5>
                            <p>Snow falls. Riders rise. Good gear makes legends.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
    </div>   

    <div class="container">
        <div class="header-quote">„There's no such thing as too much snow… just not enough gear.”</div>           
    
        <hr class="featurette-divider main-hr">
    
        <div class="row featurette">
            <div class="col-md-7">
            <p class="featurette-heading fw-normal lh-1 section-text">From Beginner to Pro — We’ve Got You Covered</p>
            <p class="lead">Looking for the perfect gear to make the most out of your time on the slopes? You’ve just found it.
            At Snowflake, we provide a wide selection of high-quality ski and snowboard equipment tailored to every skill level. Whether you’re a beginner or an experienced pro, our expert staff is here to help you find the perfect fit. Our gear is modern, well-maintained, and ready to perform, ensuring you have everything you need for an enjoyable day on the mountain.</p>
            <p class="lead">Whether you’re carving your first turns or chasing fresh powder like a pro, our wide range of modern, meticulously maintained ski and snowboard equipment means there’s something here for everyone. From beginner-friendly sets to high-performance gear, we've got you covered — in every size, style, and snow-day mood.</p>
            
            <p class="lead">So come on in — your next great ride starts here.</p>
            <p class="lead">Fresh gear. Expert service. No stress. Just snow.</p>
            </div>
            <div class="col-md-5">
            <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="{{ HOME_TEST4 }}" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)"/></img>
            </div>
        </div>
    
        <hr class="featurette-divider main-hr">
    
        <div class="row featurette">
            <div class="col-md-7 order-md-2">
            <p class="featurette-heading fw-normal lh-1 section-text">Your Adventure Begins with the Right Gear – We’re Here to Help</p>
            <p class="lead">Our passionate, experienced crew is always ready to help you gear up, get the right fit, and hit the mountain with confidence. We care about your comfort, your safety, and your stoke level.</p>
            <p class="lead">From the moment you walk through the door, our team is here to ensure you have everything you need to make the most of your time on the slopes. Whether you’re new to skiing or snowboarding or a seasoned pro, we take the time to listen, answer questions, and offer expert advice tailored to your needs. With years of experience and a genuine love for the sport, we’re dedicated to providing top-notch service and making sure every piece of equipment is perfectly suited to you. Rest assured, when you’re with us, you’re in good hands.</p>
            </div>
            <div class="col-md-5 order-md-1">
            <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="{{ HOME_TEST5 }}" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)"/></img>
            </div>
        </div>
    
        <hr class="featurette-divider main-hr">
    
        <div class="row featurette">
            <div class="col-md-7">
            <p class="featurette-heading fw-normal lh-1 section-text">Rent, Ride, Repeat: Your Perfect Equipment Awaits</p>
            <p class="lead">At Snowflake, we make renting ski and snowboard gear easy and hassle-free. Our simple reservation system lets you secure the perfect equipment in just a few clicks, so you can spend more time on the slopes and less time worrying about your gear. Whether you’re planning your next adventure or need a last-minute fit, we’ve got you covered with a wide range of high-quality equipment.</p>
            <p class="lead">When you visit us, our professional team is here to guide you every step of the way. From choosing the right gear to ensuring a perfect fit, we’ll make sure you’re equipped to hit the mountain with confidence. Want to try something new? We encourage you to test different equipment and explore new styles of skis or boards, so you can find the gear that suits your riding style and preferences. It’s all part of the fun!</p>
            <p class="lead">Renting has never been more convenient, and with our modern, well-maintained equipment, you can be sure you’re riding with the best. No need to invest in gear you’ll only use a few times a year – our rentals offer flexibility, affordability, and a chance to try something new every time you hit the snow. Plus, you’ll always have access to the latest models and technology, ensuring your ride is optimized for the best performance on the mountain.</p>
            <p class="lead">So why not join us for some great fun, top-notch equipment, and expert service? Whether you’re a beginner or a seasoned pro, we’ve got everything you need to make your next trip unforgettable.</p>
            </div>
            <div class="col-md-5">
            <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="{{ HOME_TEST6 }}" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)"/></img>
            </div>
        </div>        
    </div>
{% endblock content %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="d-flex flex-column h-100">
    <nav class="navbar navbar-expand-sm">
        <div class="container-fluid">
            <a class="nav-link navbar-brand" href="/">Snowflake</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reservations:equipment_list' %}">Equipment</a>
                    </li>      
                    <li class="nav-item">
                        <a class="nav-link" href="/about">About</a>
                    </li>
                </ul>
            </div>
            <div class="text-end">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item nav-link">
                        <a class="btn btn-outline-light me-2" href="{% url 'users:account' %}">Account</a>
                    </li>  
                    <li class="nav-item nav-link">                    
                        <form class="logout" action="{% url 'users:logout' %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-outline-light me-2">Logout</button>
                        </form>
                    </li>  
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">
                            <button class="btn btn-warning">Sign-up</button>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">
                            <button class="btn btn-outline-light me-2" title="User Login">Login</button>
                        </a>
                    </li>  
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>

    <main class="flex-shrink-0">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="footer py-3 mt-auto footer-container">
        <div class="container d-flex flex-wrap justify-content-between align-items-center inner-footer-container">
            <div class="col-md-4 d-flex align-items-center">
                <a class="nav-link navbar-brand" href="/">Snowflake</a>
            </div>          
            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3">
                    <a class="text-body-secondary" href="#" aria-label="Youtube">  
                        <img class="bi" width="24" height="24" src="{{ FOOTER_YOUTUBE }}" alt="Youtube">
                    </a>
                </li>
                <li class="ms-3">
                    <a class="text-body-secondary" href="#" aria-label="Twitter">  
                        <img class="bi" width="24" height="24" src="{{ FOOTER_TWITTER }}" alt="Twitter">
                    </a>
                </li>
                <li class="ms-3">
                    <a class="text-body-secondary" href="#" aria-label="Facebook">  
                        <img class="bi" width="24" height="24" src="{{ FOOTER_FACEBOOK }}" alt="Facebook">
                    </a>
                </li>
                <li class="ms-3">
                    <a class="text-body-secondary" href="#" aria-label="Linkedin">  
                        <img class="bi" width="24" height="24" src="{{ FOOTER_LINKEDIN }}" alt="Linkedin">
                    </a>
                </li>
            </ul>
        </div>
    </footer>
    
    <script src="{% static 'js/main.js' %}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>
